name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    concurrency: dev-deploy
    steps:
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          FLY_API_TOKEN: op://shutters-cicd/shutterkit-cdn-dev/flytoken
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg "vcs_ref=$(git rev-parse --short HEAD)"
